# Generated by Django 5.0 on 2023-12-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=500, null=True)),
                ('Prenom', models.CharField(max_length=500, null=True)),
                ('Telephone', models.CharField(max_length=500, null=True)),
                ('mail', models.CharField(max_length=500, null=True)),
                ('situation', models.CharField(choices=[('Marié', 'Marié'), ('Celibataire', 'celibataire')], max_length=500, null=True)),
                ('poste', models.CharField(choices=[('Ouvrier', 'Ouvrier'), ('Chauffeur', 'chauffeur'), ('Vendeur', 'vendeur')], max_length=200, null=True)),
                ('regime', models.CharField(choices=[('Pourcentage', 'Pourcentage'), ('Salarié', 'salarié')], max_length=200, null=True)),
                ('identité', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
