# Generated by Django 5.0 on 2023-12-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0005_alter_pers_poste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pers',
            name='poste',
            field=models.CharField(choices=[('Ouvrier', 'Ouvrier'), ('Vendeur', 'vendeur'), ('Chauffeur', 'chauffeur')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pers',
            name='regime',
            field=models.CharField(choices=[('Pourcentage', 'Pourcentage'), ('Salarié', 'salarié')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pers',
            name='situation',
            field=models.CharField(choices=[('Marié', 'Marié'), ('Celibataire', 'celibataire')], max_length=500, null=True),
        ),
    ]
