# Generated by Django 5.0 on 2023-12-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0009_alter_pers_poste_alter_pers_regime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pers',
            name='identité',
            field=models.ImageField(null=True, upload_to='.'),
        ),
    ]
