# Generated by Django 5.0 on 2023-12-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0011_alter_pers_poste'),
    ]

    operations = [
        migrations.AddField(
            model_name='pers',
            name='salaire',
            field=models.CharField(choices=[('Ouvrier', 'Ouvrier'), ('Chauffeur', 'chauffeur'), ('Vendeur', 'vendeur')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pers',
            name='regime',
            field=models.CharField(choices=[('Salarié', 'salarié'), ('Pourcentage', 'Pourcentage')], max_length=200, null=True),
        ),
    ]
