# Generated by Django 5.0 on 2023-12-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0014_alter_pers_poste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pers',
            name='situation',
            field=models.CharField(choices=[('Marié', 'Marié'), ('Celibataire', 'celibataire')], max_length=500, null=True),
        ),
    ]
