# Generated by Django 5.0 on 2023-12-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0016_alter_pers_poste_alter_pers_regime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pers',
            name='poste',
            field=models.CharField(choices=[('Vendeur', 'vendeur'), ('Ouvrier', 'Ouvrier'), ('Chauffeur', 'chauffeur')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pers',
            name='regime',
            field=models.CharField(choices=[('Salarié', 'salarié'), ('Pourcentage', 'Pourcentage')], max_length=200, null=True),
        ),
    ]
