# Generated by Django 5.0 on 2023-12-30 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0019_alter_pers_poste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pers',
            name='poste',
            field=models.CharField(choices=[('Ouvrier', 'Ouvrier'), ('Vendeur', 'vendeur'), ('Chauffeur', 'chauffeur')], max_length=200, null=True),
        ),
    ]
