# Generated by Django 5.0 on 2024-01-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0023_alter_pers_poste_alter_pers_regime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pers',
            name='poste',
            field=models.CharField(choices=[('Chauffeur', 'chauffeur'), ('Ouvrier', 'Ouvrier'), ('Vendeur', 'vendeur')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pers',
            name='situation',
            field=models.CharField(choices=[('Marié', 'Marié'), ('Celibataire', 'celibataire')], max_length=500, null=True),
        ),
    ]
