# Generated by Django 5.0 on 2024-01-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0030_alter_pers_poste_alter_pers_regime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pers',
            name='poste',
            field=models.CharField(choices=[('Ouvrier', 'Ouvrier'), ('Vendeur', 'vendeur'), ('Chauffeur', 'chauffeur')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pers',
            name='regime',
            field=models.CharField(choices=[('Salarié', 'salarié'), ('Pourcentage', 'Pourcentage')], max_length=200, null=True),
        ),
    ]
