# Generated by Django 5.0 on 2024-01-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0036_alter_pers_poste_alter_pers_regime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pers',
            name='poste',
            field=models.CharField(choices=[('Vendeur', 'vendeur'), ('Chauffeur', 'chauffeur'), ('Ouvrier', 'Ouvrier')], max_length=200, null=True),
        ),
    ]
