# Generated by Django 5.0 on 2024-01-01 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rouleaux', models.IntegerField(null=True)),
                ('emballage', models.IntegerField(null=True)),
                ('stock_rouleaux', models.IntegerField(blank=True, null=True)),
                ('stock_emballage', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
