# Generated by Django 5.0 on 2023-12-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='spend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.CharField(choices=[('usine', 'usine'), ('Toyota', 'Toyota'), ('Ford', 'FORD'), ('Citroen Jumper', 'CITROEN JUMPER'), ('autres', 'autres')], max_length=200, null=True)),
                ('type_depense', models.CharField(blank=True, choices=[('charge familliale', 'charge familliale'), ('charge ordinaire', 'charge ordinaire')], max_length=200, null=True)),
                ('detail', models.CharField(max_length=1000, null=True)),
                ('Somme_gnf', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
