# Generated by Django 5.0 on 2023-12-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spend',
            name='actif',
            field=models.CharField(choices=[('usine', 'usine'), ('Toyota', 'Toyota'), ('autres', 'autres'), ('Citroen Jumper', 'CITROEN JUMPER'), ('Ford', 'FORD')], max_length=200, null=True),
        ),
    ]
