# Generated by Django 5.0 on 2023-12-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0002_alter_spend_actif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spend',
            name='actif',
            field=models.CharField(choices=[('Toyota', 'Toyota'), ('Ford', 'FORD'), ('usine', 'usine'), ('Citroen Jumper', 'CITROEN JUMPER'), ('autres', 'autres')], max_length=200, null=True),
        ),
    ]
