# Generated by Django 5.0 on 2023-12-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0003_alter_spend_actif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spend',
            name='actif',
            field=models.CharField(choices=[('Ford', 'FORD'), ('Toyota', 'Toyota'), ('Citroen Jumper', 'CITROEN JUMPER'), ('autres', 'autres'), ('usine', 'usine')], max_length=200, null=True),
        ),
    ]
