# Generated by Django 5.0 on 2023-12-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0004_alter_spend_actif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spend',
            name='actif',
            field=models.CharField(choices=[('usine', 'usine'), ('Ford', 'FORD'), ('Citroen Jumper', 'CITROEN JUMPER'), ('autres', 'autres'), ('Toyota', 'Toyota')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='spend',
            name='type_depense',
            field=models.CharField(blank=True, choices=[('charge ordinaire', 'charge ordinaire'), ('charge familliale', 'charge familliale')], max_length=200, null=True),
        ),
    ]
