# Generated by Django 5.0 on 2023-12-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0006_alter_spend_actif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spend',
            name='actif',
            field=models.CharField(choices=[('Citroen Jumper', 'CITROEN JUMPER'), ('Ford', 'FORD'), ('usine', 'usine'), ('autres', 'autres'), ('Toyota', 'Toyota')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='spend',
            name='type_depense',
            field=models.CharField(blank=True, choices=[('charge familliale', 'charge familliale'), ('charge ordinaire', 'charge ordinaire')], max_length=200, null=True),
        ),
    ]
