# Generated by Django 5.0 on 2023-12-30 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0007_alter_spend_actif_alter_spend_type_depense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spend',
            name='actif',
            field=models.CharField(choices=[('Toyota', 'Toyota'), ('Citroen Jumper', 'CITROEN JUMPER'), ('autres', 'autres'), ('Ford', 'FORD'), ('usine', 'usine')], max_length=200, null=True),
        ),
    ]
