# Generated by Django 5.0 on 2023-12-31 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0009_alter_spend_actif_alter_spend_type_depense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spend',
            name='actif',
            field=models.CharField(choices=[('Citroen Jumper', 'CITROEN JUMPER'), ('autres', 'autres'), ('usine', 'usine'), ('Toyota', 'Toyota'), ('Ford', 'FORD')], max_length=200, null=True),
        ),
    ]
