# Generated by Django 5.0 on 2024-01-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0012_alter_spend_actif_alter_spend_type_depense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spend',
            name='actif',
            field=models.CharField(choices=[('Ford', 'FORD'), ('Citroen Jumper', 'CITROEN JUMPER'), ('Toyota', 'Toyota'), ('usine', 'usine'), ('autres', 'autres')], max_length=200, null=True),
        ),
    ]
