# Generated by Django 5.0 on 2024-01-01 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0014_alter_spend_actif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spend',
            name='actif',
            field=models.CharField(choices=[('Citroen Jumper', 'CITROEN JUMPER'), ('Toyota', 'Toyota'), ('autres', 'autres'), ('Ford', 'FORD'), ('usine', 'usine')], max_length=200, null=True),
        ),
    ]
