# Generated by Django 5.0 on 2024-01-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0020_alter_spend_actif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spend',
            name='actif',
            field=models.CharField(choices=[('autres', 'autres'), ('Citroen Jumper', 'CITROEN JUMPER'), ('Ford', 'FORD'), ('usine', 'usine'), ('Toyota', 'Toyota')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='spend',
            name='type_depense',
            field=models.CharField(blank=True, choices=[('charge familliale', 'charge familliale'), ('charge ordinaire', 'charge ordinaire')], max_length=200, null=True),
        ),
    ]
