# Generated by Django 5.0 on 2024-01-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0021_alter_spend_actif_alter_spend_type_depense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spend',
            name='actif',
            field=models.CharField(choices=[('Ford', 'FORD'), ('Toyota', 'Toyota'), ('usine', 'usine'), ('autres', 'autres'), ('Citroen Jumper', 'CITROEN JUMPER')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='spend',
            name='type_depense',
            field=models.CharField(blank=True, choices=[('charge ordinaire', 'charge ordinaire'), ('charge familliale', 'charge familliale')], max_length=200, null=True),
        ),
    ]
