# Generated by Django 5.0 on 2024-01-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depenses', '0022_alter_spend_actif_alter_spend_type_depense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spend',
            name='actif',
            field=models.CharField(choices=[('Ford', 'FORD'), ('autres', 'autres'), ('usine', 'usine'), ('Toyota', 'Toyota'), ('Citroen Jumper', 'CITROEN JUMPER')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='spend',
            name='type_depense',
            field=models.CharField(blank=True, choices=[('charge familliale', 'charge familliale'), ('charge ordinaire', 'charge ordinaire')], max_length=200, null=True),
        ),
    ]
