# Generated by Django 5.0 on 2023-12-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiale', models.CharField(max_length=500, null=True)),
                ('nombre_roulaux', models.IntegerField(null=True)),
                ('produit', models.FloatField(null=True)),
                ('sortie', models.IntegerField(blank=True, null=True)),
                ('usine', models.IntegerField(null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
