# Generated by Django 5.0 on 2023-12-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='poids',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='production',
            name='rentabilité',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='initiale',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='production',
            name='usine',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
