# Generated by Django 5.0 on 2023-12-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_production_poids_production_rentabilité_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='produit',
            field=models.IntegerField(null=True),
        ),
    ]
