# Generated by Django 5.0 on 2023-12-31 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_alter_production_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='nombre_emballage',
            field=models.IntegerField(null=True),
        ),
    ]
