# Generated by Django 5.0 on 2024-01-06 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='voitures',
            fields=[
                ('v', models.CharField(default='aucun', max_length=500, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vente', models.IntegerField(null=True)),
                ('prime', models.FloatField(blank=True, default=0, null=True)),
                ('sortie', models.IntegerField(blank=True, null=True)),
                ('vendu', models.IntegerField(null=True)),
                ('retourner', models.IntegerField(null=True)),
                ('credit', models.IntegerField(blank=True, null=True)),
                ('Somme_gnf', models.IntegerField(blank=True, null=True)),
                ('statut_credit', models.CharField(blank=True, max_length=30, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('Vehicule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vente.voitures')),
            ],
        ),
    ]
